# Generated by Django 4.2.4 on 2026-02-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('post_type', models.CharField(choices=[('job', 'Job'), ('result', 'Result'), ('admit', 'Admit Card'), ('answer', 'Answer Key'), ('syllabus', 'Syllabus'), ('vacancy', 'Vacancy')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='open', max_length=20)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('total_posts', models.CharField(blank=True, max_length=100, null=True)),
                ('age_limit', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.CharField(blank=True, max_length=150, null=True)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('notification_pdf', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('last_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('admit_card_date', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('full_desc', models.TextField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=300, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='india_app.category')),
                ('education', models.ManyToManyField(blank=True, to='india_app.educationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='india_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='india_app.postsection')),
            ],
        ),
        migrations.CreateModel(
            name='PostTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='india_app.posttable')),
            ],
        ),
        migrations.CreateModel(
            name='PostTableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_index', models.IntegerField()),
                ('value', models.TextField()),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='india_app.posttablerow')),
            ],
        ),
    ]
